stages:
  - build
  - deploy

variables:
  DOCKER_BUILDKIT: 1

# Build Docker Image
build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest 
  only:
    - main

# Deploy to Droplet
deploy:
  stage: deploy
  image: ubuntu:22.04
  before_script:
    - apt-get update
    - apt-get install -y openssh-client sshpass
  script:
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no thaidq@$SSH_HOST "cd $PATH_TO_PROJECT && docker compose pull"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no thaidq@$SSH_HOST "cd $PATH_TO_PROJECT && docker rm -f $CONTAINER_NAME"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no thaidq@$SSH_HOST "cd $PATH_TO_PROJECT && docker compose up -d"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no thaidq@$SSH_HOST "cd $PATH_TO_PROJECT && docker image prune -f"
  only:
    - main